Fully testing implenation

diff --git a/.github/workflows/end2end_test.yml b/.github/workflows/end2end_test.yml
--- a/.github/workflows/end2end_test.yml
+++ b/.github/workflows/end2end_test.yml
@@ -12,7 +12,7 @@ on:
 
 jobs:
   build:
-    runs-on: Ubuntu-22.04
+    runs-on: [Ubuntu-22.04, Ubuntu-24.04]
     timeout-minutes: 90
     steps:
     - name: Checkout
@@ -60,73 +60,70 @@ jobs:
           # Step 4: Deploy the near-Real Time RIC (3 minutes)
           cd ../../../bin 
           sudo ./deploy-ric-platform -f ../RECIPE_EXAMPLE/PLATFORM/example_recipe_oran_e_release_modified_e2.yaml
-          
-
-          sudo kubectl describe pods -n kube-flannel
-          sudo kubectl describe pods -n kube-system
+          sleep 10
           sudo kubectl get pods -A
-    # - name: Install srsRAN with E2-Like Agent
-    #   run: |
-    #       # compile srsRAN-e2 with e2-like build flags (19 minutes without running tests)
-    #       cd srsRAN-e2
-    #       mkdir build
-    #       export SRS=`realpath .`
-    #       cd build
-    #       cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo \
-    #           -DENABLE_E2_LIKE=1 \
-    #           -DENABLE_AGENT_CMD=1 \
-    #           -DRIC_GENERATED_E2AP_BINDING_DIR=${SRS}/e2_bindings/E2AP-v01.01 \
-    #           -DRIC_GENERATED_E2SM_KPM_BINDING_DIR=${SRS}/e2_bindings/E2SM-KPM \
-    #           -DRIC_GENERATED_E2SM_GNB_NRT_BINDING_DIR=${SRS}/e2_bindings/E2SM-GNB-NRT
-    #       make -j4
-    #       cd ../..
-    # - name: Install srsRAN with E2 Agent
-    #   run: |
-    #       # compile srsRAN-e2 (19 minutes without running tests)
-    #       cd srsRAN-e2
-    #       rm -rf build
-    #       mkdir build
-    #       export SRS=`realpath .`
-    #       cd build
-    #       cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo \
-    #           -DRIC_GENERATED_E2AP_BINDING_DIR=${SRS}/e2_bindings/E2AP-v01.01 \
-    #           -DRIC_GENERATED_E2SM_KPM_BINDING_DIR=${SRS}/e2_bindings/E2SM-KPM \
-    #           -DRIC_GENERATED_E2SM_GNB_NRT_BINDING_DIR=${SRS}/e2_bindings/E2SM-GNB-NRT
-    #       make -j4
-    #       #make test
-    #       sudo make install
-    #       sudo ldconfig
-    #       sudo srsran_install_configs.sh service # --force
-    # - name: Set up 5G Network
-    #   run: |
-    #       echo ">>> Adding UE1..."
-    #       sudo ip netns add ue1
-    #       echo ">>> Starting EPC..."
-    #       sudo srsepc & pid_epc=$!
-    #       echo ">>> Getting E2NODE IP..."
-    #       export E2NODE_IP=`hostname  -I | cut -f1 -d' '`
-    #       echo ">>> E2NODE IP is ${E2NODE_IP}"
-    #       export E2NODE_PORT=5006
-    #       echo ">>> Getting E2TERM IP..."
-    #       export E2TERM_IP=`sudo kubectl get svc -n ricplt --field-selector metadata.name=service-ricplt-e2term-sctp-alpha -o jsonpath='{.items[0].spec.clusterIP}'`
-    #       echo ">>> E2TERM IP is ${E2TERM_IP}"
-    #       echo ">>> Starting eNB..."
-    #       sudo srsenb --enb.n_prb=50 --enb.name=enb1 --enb.enb_id=0x19B \
-    #         --rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port0=tcp://*:2000,rx_port0=tcp://localhost:2001,tx_port1=tcp://*:2100,rx_port1=tcp://localhost:2101,id=enb,base_srate=23.04e6" \
-    #         --ric.agent.remote_ipv4_addr=${E2TERM_IP} --log.all_level=warn --ric.agent.log_level=debug --log.filename=enbLog.txt --ric.agent.local_ipv4_addr=${E2NODE_IP} --ric.agent.local_port=${E2NODE_PORT} & pid_enb=$!
-    #       echo ">>> eNB started with pid ${pid_enb}"
-    #       echo ">>> Waiting for RIC state to establish"
-    #       sleep 120
-    #       echo ">>> Starting UE..."
-    #       sudo srsue --gw.netns=ue1 & pid_ue=$!
-    #       sleep 120
-    #       echo ">>> Pinging IP address..."
+    - name: Install srsRAN with E2-Like Agent
+      run: |
+          # compile srsRAN-e2 with e2-like build flags (19 minutes without running tests)
+          cd srsRAN-e2
+          mkdir build
+          export SRS=`realpath .`
+          cd build
+          cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo \
+              -DENABLE_E2_LIKE=1 \
+              -DENABLE_AGENT_CMD=1 \
+              -DRIC_GENERATED_E2AP_BINDING_DIR=${SRS}/e2_bindings/E2AP-v01.01 \
+              -DRIC_GENERATED_E2SM_KPM_BINDING_DIR=${SRS}/e2_bindings/E2SM-KPM \
+              -DRIC_GENERATED_E2SM_GNB_NRT_BINDING_DIR=${SRS}/e2_bindings/E2SM-GNB-NRT
+          make -j4
+          cd ../..
+    - name: Install srsRAN with E2 Agent
+      run: |
+          # compile srsRAN-e2 (19 minutes without running tests)
+          cd srsRAN-e2
+          rm -rf build
+          mkdir build
+          export SRS=`realpath .`
+          cd build
+          cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo \
+              -DRIC_GENERATED_E2AP_BINDING_DIR=${SRS}/e2_bindings/E2AP-v01.01 \
+              -DRIC_GENERATED_E2SM_KPM_BINDING_DIR=${SRS}/e2_bindings/E2SM-KPM \
+              -DRIC_GENERATED_E2SM_GNB_NRT_BINDING_DIR=${SRS}/e2_bindings/E2SM-GNB-NRT
+          make -j4
+          #make test
+          sudo make install
+          sudo ldconfig
+          sudo srsran_install_configs.sh service # --force
+    - name: Set up 5G Network
+      run: |
+          echo ">>> Adding UE1..."
+          sudo ip netns add ue1
+          echo ">>> Starting EPC..."
+          sudo srsepc & pid_epc=$!
+          echo ">>> Getting E2NODE IP..."
+          export E2NODE_IP=`hostname  -I | cut -f1 -d' '`
+          echo ">>> E2NODE IP is ${E2NODE_IP}"
+          export E2NODE_PORT=5006
+          echo ">>> Getting E2TERM IP..."
+          export E2TERM_IP=`sudo kubectl get svc -n ricplt --field-selector metadata.name=service-ricplt-e2term-sctp-alpha -o jsonpath='{.items[0].spec.clusterIP}'`
+          echo ">>> E2TERM IP is ${E2TERM_IP}"
+          echo ">>> Starting eNB..."
+          sudo srsenb --enb.n_prb=50 --enb.name=enb1 --enb.enb_id=0x19B \
+            --rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port0=tcp://*:2000,rx_port0=tcp://localhost:2001,tx_port1=tcp://*:2100,rx_port1=tcp://localhost:2101,id=enb,base_srate=23.04e6" \
+            --ric.agent.remote_ipv4_addr=${E2TERM_IP} --log.all_level=warn --ric.agent.log_level=debug --log.filename=enbLog.txt --ric.agent.local_ipv4_addr=${E2NODE_IP} --ric.agent.local_port=${E2NODE_PORT} & pid_enb=$!
+          echo ">>> eNB started with pid ${pid_enb}"
+          echo ">>> Waiting for RIC state to establish"
+          sleep 120
+          echo ">>> Starting UE..."
+          sudo srsue --gw.netns=ue1 & pid_ue=$!
+          sleep 120
+          echo ">>> Pinging IP address..."
 
-    #       #timeout 5 sudo ip netns exec ue1 ping 172.16.0.1 -O -c 10 ; rc=$? # 124 for succesful ping
-    #       #if [ $rc -ne 124 ] ; then exit -1 ; fi
-    #       #echo ">>> 5G Network setup completed"
+          #timeout 5 sudo ip netns exec ue1 ping 172.16.0.1 -O -c 10 ; rc=$? # 124 for succesful ping
+          #if [ $rc -ne 124 ] ; then exit -1 ; fi
+          #echo ">>> 5G Network setup completed"
 
-    #       while ! sudo ip netns exec ue1 ping 172.16.0.1 -c3; do echo "Ping Fail"; done ; echo "5G Network setup completed" ;
+          while ! sudo ip netns exec ue1 ping 172.16.0.1 -c3; do echo "Ping Fail"; done ; echo "5G Network setup completed" ;
 
 
 
